name: MultiAiApp
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: 16.0
targets:
  MultiAiApp:
    type: application
    platform: iOS
    sources: 
      - MultiAiApp
    resources:
      - MultiAiApp/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: MultiAiApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.MultiAiApp
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon